title: Guithium
description: A starter template for a Jeykll site using the Just the Docs theme!
domain: billygalbreath.github.io
url: https://billygalbreath.github.io
baseurl: "/guithium"
github_username: billygalbreath

# https://just-the-docs.com/docs
theme: just-the-docs

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      # https://jekyllrb.com/docs/layouts/#inheritance
      # default, minimal, about, home, page, post
      layout: "default"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# External navigation links
nav_external_links:
  - title: Download on Modrinth
    url: https://modrinth.com/project/guithium
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

# Aux links for the upper right navigation
aux_links_new_tab: true
aux_links:
  javadoc: https://jd.pl3x.net/net/pl3x/guithium/guithium-api/0.0.1

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

# Footer content - appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release.
# Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/billygalbreath/guithium" # the GitHub URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# https://just-the-docs.com/docs/ui-components/callouts/
callouts_level: loud  # quiet or loud (for dark theme)
callouts:
  highlight:
    color: yellow
  note:
    color: purple
  new:
    title: New
    color: green
  important:
    title: Important
    color: blue
  warning:
    title: Warning
    color: red
  pros:
    title: Pros
    color: green
  cons:
    title: Cons
    color: red
