name: Build Snapshot
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Import gradle properties
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Publish to maven repo
        run: ./gradlew publish
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          avatar_url: https://cdn.discordapp.com/avatars/1044154256007106560/df91181b3f1cf0ef1592fbe18e0962d7.webp?size=80
          nodetail: true
          title: Dev snapshot built successfully!
          description: |
            Version ${{ env.mod_version }} Build ${{ github.run_number }}
            Click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to view the run!
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          avatar_url: https://cdn.discordapp.com/avatars/1044154256007106560/df91181b3f1cf0ef1592fbe18e0962d7.webp?size=80
          nodetail: true
          title: Dev snapshot build failure!
          color: 0xff0000
          description: |
            Version ${{ env.mod_version }} Build ${{ github.run_number }}
            Click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to view the run!
