name: Build Snapshot
on:
  push:
    branches-ignore:
      - "master"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Restore gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Read Version Catalog
        uses: SebRollen/toml-action@v1.2.0
        id: version
        with:
          file: "gradle/libs.versions.toml"
          field: "versions.guithium"

      - name: Set Version Number
        run: |
          VERSION=${{ steps.version.outputs.value }}-SNAPSHOT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION is $VERSION"

      - name: Build Snapshot
        run: ./gradlew build publish --stacktrace --no-daemon

      - name: Upload Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Guithium-${{ env.VERSION }}"
          path: build/libs/*.jar
