name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Import gradle properties
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Generate Javadoc
        run: ./gradlew javadoc
      - name: Publish to maven repo
        run: ./gradlew publish
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: api/build/docs/javadoc
          target-folder: ./
      - name: Publish to Modrinth
        run: ./gradlew modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: New build of Guithium is ready!
          description: |
            Version ${{ env.mod_version }}+${{ github.run_number }}
            Click [here](https://modrinth.com/mod/guithium) to download!
