name: Build Release
on:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Restore gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}

      - name: Read Version Catalog
        uses: SebRollen/toml-action@v1.2.0
        id: version
        with:
          file: "gradle/libs.versions.toml"
          field: "versions.guithium"

      - name: Set Version Number
        run: |
          VERSION=${{ steps.version.outputs.value }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION is $VERSION"

      - name: Build Release
        run: ./gradlew build publish modrinth --stacktrace --no-daemon
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}

      - name: Notify Discord
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          nodetail: true
          title: New build of Guithium is ready!
          description: |
            Version ${{ env.VERSION }}
            Click [here](https://modrinth.com/mod/guithium) to download!

      - name: Notify Discord
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          nodetail: true
          title: Build Failure!
          color: 0xff0000
          description: |
            Version ${{ env.VERSION }}
            Click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to view the run!
