name: Build Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21
      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
          cat gradle.properties >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Deploy Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: javadoc
          clean: true
          folder: api/build/docs/javadoc
          target-folder: ./
      - name: Publish to Modrinth
        run: ./gradlew modrinth --stacktrace
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>') }}
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          nodetail: true
          title: New build of Guithium is ready!
          description: |
            Version ${{ env.mod_version }} Build ${{ github.run_number }}
            Click [here](https://modrinth.com/mod/guithium) to download!
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_BUILDS_WEBHOOK }}
          nodetail: true
          title: Build Failure!
          color: 0xff0000
          description: |
            Version ${{ env.mod_version }} Build ${{ github.run_number }}
            Click [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) to view the run!
