name: Build Snapshot
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: guithium-snapshot
          path: build/libs/*.jar
