name: Pull Requests
on:
  pull_request:
    branches-ignore:
      - "master"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --stacktrace --no-daemon
