name: Pull Requests
on: [ pull_request ]

jobs:
  run:
    if: |
      github.repository != github.event.pull_request.head.repo.full_name &&
      (
        github.head_ref != 'master' ||
        github.event.pull_request.head.repo.owner.type == 'User'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --stacktrace
