name: "Guithium"
main: "net.pl3x.guithium.plugin.GuithiumPlugin"
version: "${version}"
api-version: "${minecraft}"
description: "Allows paper servers to add GUIs to your fabric client"
author: "BillyGalbreath"
